import test from 'node:test';import assert from 'node:assert/strict';import {dashboardMetrics,periodRange,hiredDate} from '../src/dashboard-metrics.js';
const range=periodRange('Custom','2026-01-01','2026-01-31',new Date('2026-02-15T10:00:00Z'));
const jobs=[{id:'j',title:'Engineer',dept:'A',entity:'Egypt',status:'Open',headcount:3,recordedOpenDate:'2025-12-01',targetCloseDate:'2026-01-01',recruiterIds:['u','v']}];
const candidates=[{id:'c',name:'C',source:'referral'}];const applications=[{id:'a',jobId:'j',candidateId:'c',stage:'Hired',status:'Active',appliedDate:'2026-01-02',stageHistory:[{toStage:'hired',movedAt:'2026-01-21T10:00:00Z'}],lastActivityAt:'2026-02-14'}];
test('hires use event date, not edits; missing event is excluded',()=>{const m=dashboardMetrics({jobs,candidates,applications:[...applications,{...applications[0],id:'b',stageHistory:[]}],range});assert.equal(m.hires.length,1);assert.equal(m.fillMean,51);assert.equal(m.quality[0].rows.length,1);assert.equal(m.totalHC,3)});
test('organization filters cannot retain applications or offers outside eligible jobs',()=>{const m=dashboardMetrics({jobs,candidates,applications,offers:[{id:'o',applicationId:'a',rawStatus:'sent'}],entity:'Cyprus',range});assert.equal(m.apps.length,0);assert.equal(m.offers.length,0);assert.equal(m.totalHC,0)});
test('acceptance is decision dated and pending excludes drafts',()=>{const offers=[{id:'o',jobId:'j',rawStatus:'accepted',acceptedAt:'2026-01-15'},{id:'d',jobId:'j',rawStatus:'declined',declinedAt:'2026-01-16'},{id:'x',jobId:'j',rawStatus:'accepted'},{id:'p',jobId:'j',rawStatus:'sent',sentAt:'2026-02-01'},{id:'draft',jobId:'j',rawStatus:'draft'}];const m=dashboardMetrics({jobs,candidates,applications,offers,range});assert.equal(m.acceptance,50);assert.equal(m.pending.length,1);assert.equal(m.quality[5].rows.length,1)});
test('source cohort counts each candidate once; shared recruiter assignment not lost',()=>{const active=applications.map(a=>({...a,stage:'Technical Interview'}));const m=dashboardMetrics({jobs,candidates,applications:active,range});assert.equal(m.sources[0].applicants.length,1);assert.equal(m.recruiters.length,2);assert.equal(m.recruiters[0].apps.length,1);assert.equal(m.recruiters[1].apps.length,1)});
test('period previous window is equal length and hire date uses earliest event',()=>{assert.equal(range.previousEnd,'2025-12-31');assert.equal(range.previousStart,'2025-12-01');assert.equal(hiredDate({stageHistory:[{toStage:'hired',movedAt:'2026-03-01'},{toStage:'hired',movedAt:'2026-01-02'}]}),'2026-01-02')});
