import { recruitmentAnalysis } from './recruitment-analysis.js';
const DAY=86400000;
// User confirmed these existing undated Hired records belong to 2026 on 7 October.
// Reporting attribution only: do not fabricate hire dates or assign them to a month.
export const CONFIRMED_2026_HIRES=new Set([
 'cmupa03ns00ei5yr2muwbsyki','cmup8qoci00ak5yr2n65o49dm',
 'cmul7tkfz015q11gkdjrrriou','cmsx4k1ja00l76eg2os25d1bn',
 'cmsvu0t4k00dh6eg2falszukf','cmseocra3009otccqocot5q3u',
 'cmrkg675u00ha6j5lucglbre4','cmqgqi2nn004tngfhzxw2wt7h'
]);
export function day(value){if(!value)return null; if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const d=new Date(value);if(!Number.isFinite(+d))return null;return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
export function days(a,b){return Math.round((Date.parse(b)-Date.parse(a))/DAY)}
const shift=(date,n)=>new Date(Date.parse(date)+n*DAY).toISOString().slice(0,10);
export function periodRange(mode,customStart,customEnd,now=new Date()) {const today=day(now);const [y,m]=today.split('-').map(Number);let start=mode==='Month'?`${y}-${String(m).padStart(2,'0')}-01`:mode==='Quarter'?`${y}-${String(Math.floor((m-1)/3)*3+1).padStart(2,'0')}-01`:`${y}-01-01`;let end=today;if(mode==='Custom'){start=customStart||start;end=customEnd&&customEnd<today?customEnd:today;}const valid=!!start&&!!end&&start<=end;const length=valid?days(start,end)+1:0;return {start,end,valid,previousStart:shift(start,-length),previousEnd:shift(start,-1),today};}
export const within=(value,start,end)=>{const d=day(value);return !!d&&d>=start&&d<=end};
export function hiredDate(app){return (app.stageHistory||[]).filter(e=>e.toStage==='hired'||e.toDisplayStage==='Hired').map(e=>day(e.movedAt)).filter(Boolean).sort()[0]||null;}
export const mean=rows=>rows.length?rows.reduce((s,r)=>s+r.days,0)/rows.length:null;
export function positionCategory(job){const raw=String(job?.recordedPositionType ?? job?.positionType ?? '').trim();return /^additional (r\.?|resource[s]?)$/i.test(raw)?'Additional Resource':raw||'Not recorded';}
export function hireEmploymentType(job){const category=positionCategory(job).toLowerCase();if(category==='internship')return 'Interns';if(category==='project hire')return 'Project hires';return ({full_time:'FTE',part_time:'Part-time',contract:'Contract',internship:'Interns'})[job?.employmentType]||'Not recorded';}
const groupRecords=(rows,label)=>{const groups=new Map();for(const row of rows){const key=label(row);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}return [...groups].map(([label,rows])=>({label,rows,count:rows.length})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label));};
export function dashboardMetrics({jobs=[],candidates=[],applications=[],offers=[],interviews=[],users=[],entity='',department='',range}){
 const js=jobs.filter(j=>(!entity||(j.entity||'Unassigned')===entity)&&(!department||(j.dept||'Unassigned')===department));const jm=new Map(js.map(j=>[j.id,j]));const cm=new Map(candidates.map(c=>[c.id,c]));
 const apps=applications.filter(a=>jm.has(a.jobId));const am=new Map(apps.map(a=>[a.id,a]));const os=offers.filter(o=>jm.has(o.jobId)||am.has(o.applicationId));const ins=interviews.filter(i=>am.has(i.applicationId));const scopedCandidates=candidates.filter(c=>apps.some(a=>a.candidateId===c.id)||(!entity&&!department));
 const record=a=>({id:a.id,candidate:cm.get(a.candidateId)?.name||'Candidate',position:jm.get(a.jobId)?.title||'Unassigned',department:jm.get(a.jobId)?.dept||'Unassigned',stage:a.stage,applied:day(a.appliedDate),hired:hiredDate(a)});
 const appRows=rows=>rows.map(record);const jobRows=rows=>rows.map(j=>({id:j.id,position:j.title,department:j.dept,entity:j.entity,status:j.status,headcount:j.headcount,opened:j.recordedOpenDate||null,target:j.targetCloseDate||null}));const offerRows=rows=>rows.map(o=>({id:o.id,candidate:cm.get(am.get(o.applicationId)?.candidateId)?.name||o.candidateName||'Candidate',position:jm.get(o.jobId||am.get(o.applicationId)?.jobId)?.title||o.jobTitle,status:o.rawStatus||o.status,sent:o.sentAt,accepted:o.acceptedAt,declined:o.declinedAt}));
 const hirePool=apps.filter(a=>a.stage==='Hired');
 const confirmedUndated=hirePool.filter(a=>range.valid&&range.start==='2026-01-01'&&range.end>='2026-10-07'&&range.end<='2026-12-31'&&!hiredDate(a)&&CONFIRMED_2026_HIRES.has(a.id));
 const hires=hirePool.filter(a=>range.valid&&(within(hiredDate(a),range.start,range.end)||confirmedUndated.includes(a)));const previousHires=hirePool.filter(a=>range.valid&&within(hiredDate(a),range.previousStart,range.previousEnd));
 const positionDate=j=>j.recordedOpenDate||j.createdAt;
 const periodPositions=js.filter(j=>range.valid&&within(positionDate(j),range.start,range.end));
 const previousPositions=js.filter(j=>range.valid&&within(positionDate(j),range.previousStart,range.previousEnd));
 const positionBreakdown=groupRecords(periodPositions,positionCategory);
 const hireBreakdown=groupRecords(hires,a=>hireEmploymentType(jm.get(a.jobId)));
 const positionDetailRows=periodPositions.map(j=>({...jobRows([j])[0],category:positionCategory(j),reportingDate:day(positionDate(j)),dateBasis:j.recordedOpenDate?'Opening date':'Creation date'}));
 const hireDetailRows=hires.map(a=>({...record(a),employmentType:hireEmploymentType(jm.get(a.jobId)),positionCategory:positionCategory(jm.get(a.jobId))}));
 const hcBreakdown=groupRecords(js,positionCategory).map(g=>({...g,count:g.rows.reduce((sum,j)=>sum+(Number(j.headcount)||1),0)}));
 const hireAuditRows=hirePool.map(a=>({...record(a),candidateId:a.candidateId,included:confirmedUndated.includes(a)?'Included · confirmed 2026, date missing':hires.includes(a)?'Included':!hiredDate(a)?'Missing hire date':'Outside selected period',lastEdited:day(a.lastActivityAt)}));
 const hireAudit={total:hirePool.length,included:hires.length,missing:hirePool.filter(a=>!hiredDate(a)).length,outside:hirePool.filter(a=>hiredDate(a)&&!hires.includes(a)).length,uniqueIncluded:new Set(hires.map(a=>a.candidateId)).size};
 const fill=rows=>rows.flatMap(a=>{const start=day(jm.get(a.jobId)?.recordedOpenDate);const end=hiredDate(a);return start&&end&&end>=start?[{...record(a),opened:start,days:days(start,end)}]:[]});const fillRows=fill(hires),previousFill=fill(previousHires);
 const decisionDate=o=>(o.rawStatus||'').toLowerCase()==='accepted'?o.acceptedAt:o.declinedAt;const decided=os.filter(o=>['accepted','declined'].includes((o.rawStatus||'').toLowerCase()));const decisions=decided.filter(o=>range.valid&&within(decisionDate(o),range.start,range.end));const prevDecisions=decided.filter(o=>range.valid&&within(decisionDate(o),range.previousStart,range.previousEnd));const rate=rows=>rows.length?rows.filter(o=>o.rawStatus==='accepted').length/rows.length*100:null;
 const open=js.filter(j=>j.status==='Open');const overdue=open.filter(j=>day(j.targetCloseDate)&&day(j.targetCloseDate)<range.today);const pending=os.filter(o=>o.rawStatus==='sent');const oldOffers=pending.filter(o=>day(o.sentAt)&&days(day(o.sentAt),range.today)>5);const veryOld=oldOffers.filter(o=>days(day(o.sentAt),range.today)>10);
 const noCandidates=open.filter(j=>day(j.recordedOpenDate)&&days(day(j.recordedOpenDate),range.today)>=14&&!apps.some(a=>a.jobId===j.id&&within(a.appliedDate,shift(range.today,-13),range.today)));
 const feedback=ins.filter(i=>i.status!=='Cancelled'&&i.scheduledAt&&Date.parse(i.scheduledAt)<Date.now()-DAY&&!i.feedbackSubmitted);
 const alerts=[{label:'Requisitions past target date',severity:'risk',rows:jobRows(overdue)},{label:'Offers pending more than 10 days',severity:'risk',rows:offerRows(veryOld)},{label:'Offers pending 6–10 days',severity:'watch',rows:offerRows(oldOffers.filter(o=>!veryOld.includes(o)))},{label:'Interviews missing feedback',severity:'watch',rows:feedback.map(i=>({...record(am.get(i.applicationId)),interviewId:i.id,scheduled:i.scheduledAt,feedback:'Missing after 24 hours'}))},{label:'No new candidates in 14 days',severity:'watch',rows:jobRows(noCandidates)}].filter(a=>a.rows.length).sort((a,b)=>(a.severity==='risk'?0:1)-(b.severity==='risk'?0:1)||b.rows.length-a.rows.length);
 const cohort=apps.filter(a=>range.valid&&within(a.appliedDate,range.start,range.end));
 const analysisApps=cohort.map(a=>{const hist=(a.stageHistory||[]).filter(e=>within(e.movedAt,'0001-01-01',range.end));const last=[...hist].sort((a,b)=>String(a.movedAt).localeCompare(String(b.movedAt))).at(-1);return {...a,stageHistory:hist,stage:range.end===range.today?a.stage:(last?.toDisplayStage||({applied:'Applied',screening:'HR Screening',assessment:'Technical Interview',offer:'Offer',hired:'Hired',rejected:'Rejected'}[last?.toStage])||'Applied')};});
 const analysis=recruitmentAnalysis(scopedCandidates,analysisApps);const perCandidate=new Map();for(const a of analysisApps){if(!perCandidate.has(a.candidateId))perCandidate.set(a.candidateId,[]);perCandidate.get(a.candidateId).push(a);}const stageDetails=new Map();for(const [id,list]of perCandidate){const c=cm.get(id);if(c)stageDetails.set(id,recruitmentAnalysis([c],list));}
 const stageRows=(label,key)=>[...stageDetails].filter(([,a])=>a.pipelineRows.find(r=>r.label===label)?.[key]>0).map(([id])=>({id,candidate:cm.get(id)?.name,stage:label,metric:key}));const routeRows=route=>[...stageDetails].filter(([,a])=>a.transitions.some(t=>t.from===route.from&&t.to===route.to)).map(([id])=>({id,candidate:cm.get(id)?.name,from:route.from,to:route.to}));
 const sourceMap=new Map();
 const sourceGroup=id=>{const source=String(cm.get(id)?.source||'Unknown').trim().toLowerCase()||'unknown';if(!sourceMap.has(source))sourceMap.set(source,{source,applicants:[],hires:[],cohortHires:[]});return sourceMap.get(source)};
 for(const [id]of perCandidate){const g=sourceGroup(id);const row={id,candidate:cm.get(id)?.name||'Candidate',source:g.source};g.applicants.push(row);if(hirePool.some(a=>a.candidateId===id&&((hiredDate(a)&&hiredDate(a)<=range.end)||confirmedUndated.includes(a))))g.cohortHires.push(row);}
 for(const a of hires){const g=sourceGroup(a.candidateId);g.hires.push({...record(a),source:g.source});}
 const sources=[...sourceMap.values()].sort((a,b)=>b.hires.length-a.hires.length||a.source.localeCompare(b.source));const sourceHires=sources.reduce((s,r)=>s+r.hires.length,0);

 const deptMap=new Map();js.forEach(j=>{const d=j.dept||'Unassigned';if(!deptMap.has(d))deptMap.set(d,{department:d,jobs:[],hires:[],open:[],fill:[]});deptMap.get(d).jobs.push(j);if(j.status==='Open')deptMap.get(d).open.push(j)});hires.forEach(a=>deptMap.get(jm.get(a.jobId)?.dept||'Unassigned')?.hires.push(a));fillRows.forEach(r=>deptMap.get(r.department)?.fill.push(r));const departments=[...deptMap.values()].map(r=>{const planned=r.jobs.reduce((s,j)=>s+(Number(j.headcount)||1),0);const dated=r.open.filter(j=>day(j.recordedOpenDate)&&day(j.recordedOpenDate)<=range.today);return {...r,planned,gap:Math.max(0,planned-r.hires.length),percent:planned?r.hires.length/planned*100:null,averageOpen:dated.length?dated.reduce((s,j)=>s+days(day(j.recordedOpenDate),range.today),0)/dated.length:null}}).sort((a,b)=>b.gap-a.gap||a.department.localeCompare(b.department));
 const active=apps.filter(a=>a.status==='Active'&&!['Hired','Rejected','On Hold'].includes(a.stage));const workload=new Map();const ensure=(id,name)=>{if(!workload.has(id))workload.set(id,{id,name,apps:[],jobs:[]});return workload.get(id)};if(!entity&&!department)users.filter(u=>u.active!==false&&['Recruiter','recruiter'].includes(u.role)).forEach(u=>ensure(u.id,u.fullName));js.forEach(j=>{const ids=j.recruiterIds?.length?j.recruiterIds:[j.recruiterId||'unassigned'];ids.forEach((id,i)=>{const user=users.find(u=>u.id===id);const r=ensure(id,user?.fullName||j.recruiterNames?.[i]||j.recruiter||'Unassigned');if(j.status==='Open')r.jobs.push(j);r.apps.push(...active.filter(a=>a.jobId===j.id))})});const recruiters=[...workload.values()].sort((a,b)=>b.apps.length-a.apps.length||a.name.localeCompare(b.name));const workloadMean=recruiters.length?recruiters.reduce((s,r)=>s+r.apps.length,0)/recruiters.length:0;
 const monthly=[];if(range.valid){let d=range.start.slice(0,7)+'-01';while(d<=range.end&&monthly.length<120){const next=new Date(Date.parse(d));next.setUTCMonth(next.getUTCMonth()+1);const nextDay=next.toISOString().slice(0,10);const rows=hires.filter(a=>hiredDate(a)>=d&&hiredDate(a)<nextDay);monthly.push({month:d.slice(0,7),rows,cumulative:hires.filter(a=>hiredDate(a)<nextDay).length});d=nextDay;}}
 const repeats=hirePool.filter(a=>hirePool.filter(b=>b.candidateId===a.candidateId).length>1);
 const quality=[{label:'Hired records without a recorded hire event date',rows:appRows(hirePool.filter(a=>!hiredDate(a)))},{label:'Hired candidate IDs with multiple applications',rows:appRows(repeats)},{label:'Selected hires without usable opening / hire dates',rows:appRows(hires.filter(a=>!fillRows.some(r=>r.id===a.id)))},{label:'Open requisitions missing target dates',rows:jobRows(open.filter(j=>!day(j.targetCloseDate)))},{label:'Open requisitions missing opening dates',rows:jobRows(open.filter(j=>!day(j.recordedOpenDate)))},{label:'Decided offers missing decision dates',rows:offerRows(decided.filter(o=>!day(decisionDate(o))))},{label:'Sent offers missing sent date',rows:offerRows(pending.filter(o=>!day(o.sentAt)))},{label:'Incomplete stage history in selected cohort',rows:appRows(analysisApps.filter(a=>!a.stageHistory?.length&&a.stage!=='Applied'))}];
 return {confirmedUndated,hcBreakdown,hireAudit,hireAuditRows,periodPositions,previousPositions,positionBreakdown,hireBreakdown,positionDetailRows,hireDetailRows,jobs:js,apps,candidates:scopedCandidates,offers:os,open,hires,previousHires,fillRows,fillMean:mean(fillRows),previousFillMean:mean(previousFill),decisions,acceptance:rate(decisions),previousAcceptance:rate(prevDecisions),pending,oldOffers,overdue,alerts,analysis,stageRows,routeRows,sources,sourceHires,departments,recruiters,workloadMean,monthly,quality,appRows,jobRows,offerRows,totalHC:js.reduce((s,j)=>s+(Number(j.headcount)||1),0)};
}
