import React,{useEffect,useMemo,useRef,useState} from 'react';
import {dashboardMetrics,periodRange,day,days,mean} from './dashboard-metrics.js';
import './ManagementDashboard.css';
const rounded=n=>n===null||n===undefined?'—':Math.round(n).toLocaleString();
const pct=n=>n===null?'—':`${rounded(n)}%`;
const colors=['#55C4EB','#A7D542','#FAA626','#58595B','#F24B4B'];
const progress=n=>n===null?'neutral':n<50?'risk':n<=80?'watch':'good';
const statusText={neutral:'Not assessed',risk:'At risk',watch:'Watch',good:'On track'};
function Badge({state='neutral',children}){return <span className={`md-status ${state}`}>{children||statusText[state]}</span>}
function Trend({now,previous,unit=''}){return <small>{now===null||previous===null?'Trend unavailable':`${now>=previous?'↑':'↓'} ${rounded(Math.abs(now-previous))}${unit} vs prior equal period`}</small>}
function Detail({detail,onClose}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal()},[]);const columns=[...new Set(detail.rows.flatMap(r=>Object.keys(r)))];return <dialog className="md-dialog" ref={ref} onCancel={onClose} aria-labelledby="md-detail-title"><header><div><h2 id="md-detail-title">{detail.title}</h2><p>{detail.scope} · {detail.rows.length} records</p></div><button className="btn" onClick={onClose}>Close</button></header><div className="table-wrap">{detail.rows.length?<table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{detail.rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{r[c]===null||r[c]===undefined?'Not recorded':String(r[c])}</td>)}</tr>)}</tbody></table>:<p>No qualifying records. Missing or unavailable source data is reported separately.</p>}</div>{detail.note&&<p className="md-note">{detail.note}</p>}</dialog>}
export default function ManagementDashboard({jobs=[],candidates=[],applications=[],offers=[],interviews=[],allUsers=[],loadedAt,dataError,reloadData}){
 const [mode,setMode]=useState('YTD'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[entity,setEntity]=useState(''),[department,setDepartment]=useState(''),[view,setView]=useState('pipeline'),[all,setAll]=useState(false),[detail,setDetail]=useState(null),[refreshing,setRefreshing]=useState(false),[refreshError,setRefreshError]=useState('');
 const range=periodRange(mode,from,to);const scope=`${range.start} – ${range.end} · ${entity||'All accessible entities'} · ${department||'All accessible departments'}`;
 const m=useMemo(()=>dashboardMetrics({jobs,candidates,applications,offers,interviews,users:allUsers,entity,department,range}),[jobs,candidates,applications,offers,interviews,allUsers,entity,department,range.start,range.end,range.today]);
 const open=(title,rows,note='',current=false)=>setDetail({title,rows,note,scope:current?`Current · ${entity||'All accessible entities'} · ${department||'All accessible departments'}`:scope});
 const num=(value,title,rows,note='',current=false)=><button className="md-number" title={title} onClick={()=>open(title,rows,note,current)}>{value}</button>;
 const refresh=async()=>{setRefreshing(true);setRefreshError('');try{await reloadData?.()}catch(e){setRefreshError(e.message||'Refresh failed')}finally{setRefreshing(false)}};
 const missingHires=m.quality[0].rows.length;
 const fillStatus=m.fillMean===null?'neutral':m.fillMean<=50?'good':m.fillMean<=60?'watch':'risk';
 const acceptStatus=m.acceptance===null?'neutral':m.acceptance>=80?'good':m.acceptance>=50?'watch':'risk';
 const accepted=m.decisions.filter(o=>o.rawStatus==='accepted').length;
 const planRate=m.totalHC?m.hires.length/m.totalHC*100:null;
 const stageMax=Math.max(1,...m.analysis.pipelineRows.map(r=>r.reached));const biggest=m.analysis.pipelineRows.filter(r=>r.rejected>0).sort((a,b)=>b.rejected-a.rejected)[0];
 const sourceHidden=m.sources.filter(r=>r.source==='other'&&m.sourceHires&&r.hires.length/m.sourceHires<.05);const sources=m.sources.filter(r=>!sourceHidden.includes(r));
 const fillDepartments=m.departments.filter(r=>r.fill.length).sort((a,b)=>mean(b.fill)-mean(a.fill));const meanMax=Math.max(50,...fillDepartments.map(r=>mean(r.fill)));
 const hireTrendRows=m.monthly;const chartMax=Math.max(1,...hireTrendRows.map(r=>r.cumulative));
 const planRows=all?m.departments:m.departments.slice(0,8);const totalOpenDated=m.open.filter(j=>day(j.recordedOpenDate)&&day(j.recordedOpenDate)<=range.today);const averageOpen=totalOpenDated.length?totalOpenDated.reduce((s,j)=>s+days(day(j.recordedOpenDate),range.today),0)/totalOpenDated.length:null;
 const cards=[
 {label:`Total positions ${mode}`,value:m.periodPositions.length,scope:'Requisition records · all statuses',state:'neutral',status:'Recorded total',target:`${m.periodPositions.reduce((sum,j)=>sum+(Number(j.headcount)||1),0)} requested headcount`,breakdown:m.positionBreakdown,trend:<Trend now={m.periodPositions.length} previous={m.previousPositions.length}/>,definition:'Requisition records opened in the selected period, using creation date when opening date is missing; all statuses included. Breakdown is by position category.',rows:m.positionDetailRows,note:'One requisition counts once even when it requests multiple people. Opening date is used first, otherwise creation date; the date basis is shown for each record.'},
 {label:`Hires ${mode}`,value:m.hires.length,scope:'Recorded hire events in period',state:'neutral',status:'Recorded hires',target:`${pct(planRate)} of ${m.totalHC} total requested HC`,breakdown:m.hireBreakdown,trend:<Trend now={m.hires.length} previous={m.previousHires.length}/>,definition:'Hired application records with a recorded Hired event in the selected period, grouped by employment type; Internship and Project Hire position categories take precedence.',rows:m.hireDetailRows,note:`${missingHires} undated hired records excluded. Internship and Project Hire categories identify interns and project hires; remaining records use the recorded employment type. Missing types are shown as Not recorded. Each hired application counts once.`},
 {label:'Recruitment target achieved',value:pct(planRate),scope:`${mode} hires / total requested headcount`,state:progress(planRate),target:`${m.hires.length} hired ÷ ${m.totalHC} total HC · target 100%`,trend:'All requisition statuses included',definition:'Hired application records in the selected period divided by total requested headcount across all accessible requisitions, including drafts.',rows:m.hireDetailRows,note:`${m.hires.length} dated hires ÷ ${m.totalHC} total requested headcount = ${pct(planRate)}. Headcount counts people requested, not requisition records. ${missingHires} undated hired records excluded. Completion bands: below 50% at risk, 50–80% watch, above 80% on track; these do not measure annual plan pace.`},
 {label:'Time to fill',value:m.fillMean===null?'—':`${rounded(m.fillMean)}d`,scope:'Selected hire period',state:fillStatus,target:'Target ≤50 days',trend:<Trend now={m.fillMean} previous={m.previousFillMean} unit="d"/>,definition:'Average calendar days from recorded requisition opening to first Hired event, for hires in this period.',rows:m.fillRows},
 {label:'Offer acceptance',value:pct(m.acceptance),scope:'Decision dates in period',state:acceptStatus,target:`${accepted} accepted / ${m.decisions.length} decided · target ≥80%`,trend:<Trend now={m.acceptance} previous={m.previousAcceptance} unit=" pp"/>,definition:'Accepted offers divided by accepted plus declined offers with decision dates in the period.',rows:m.offerRows(m.decisions)},
 {label:'Pending offers',value:m.pending.length,scope:'Current · sent to candidate',state:m.oldOffers.length?'watch':m.quality[6].rows.length?'neutral':'good',target:`${m.oldOffers.length} older than 5d · target 0`,trend:'Historical snapshot unavailable',definition:'Sent offers awaiting candidate response; excludes drafts and internal approvals.',rows:m.offerRows(m.pending),current:true}
 ];
 return <div className="management-dashboard md-v2"><header className="md-header"><div><h1>Karm. ATS Dashboard</h1><p>Live ATS data · {loadedAt?`updated ${new Date(loadedAt).toLocaleString('en-GB',{timeZone:'Africa/Cairo'})} Cairo`:'awaiting first successful refresh'}</p></div><button className="btn" onClick={refresh} disabled={refreshing}>{refreshing?'Refreshing…':'Refresh'}</button></header>
 <div className="md-filters"><fieldset><legend>Reporting period</legend>{['Month','Quarter','YTD','Custom'].map(p=><button key={p} className={p===mode?'selected':''} aria-pressed={p===mode} onClick={()=>setMode(p)}>{p}</button>)}</fieldset>{mode==='Custom'&&<><label>From<input type="date" value={from} max={range.today} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} max={range.today} onChange={e=>setTo(e.target.value)}/></label></>}<label>Entity<select value={entity} onChange={e=>{setEntity(e.target.value);setDepartment('')}}><option value="">All accessible entities</option>{[...new Set(jobs.map(j=>j.entity||'Unassigned'))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">All accessible departments</option>{[...new Set(jobs.filter(j=>!entity||(j.entity||'Unassigned')===entity).map(j=>j.dept||'Unassigned'))].sort().map(x=><option key={x}>{x}</option>)}</select></label></div>
 <p className="md-scope-line">{scope} · Current metrics show today’s operational state.</p>{!range.valid&&<p role="alert">Choose an end date on or after the start date.</p>}{(dataError||refreshError)&&<p className="md-warning" role="alert">Refresh failed. Displayed data may be stale: {dataError||refreshError}</p>}
 <div className={`md-kpis ${refreshing?'md-loading':''}`} aria-busy={refreshing}>{cards.map(c=><button className={`md-kpi ${c.state}`} key={c.label} title={c.definition} onClick={()=>open(c.label,c.rows,c.note||c.definition,c.current)}><span>{c.label} ⓘ</span><div className="md-kpi-scope">{c.scope}</div><strong>{c.value}</strong><Badge state={c.state}>{c.status}</Badge>{c.breakdown&&<div className="md-kpi-breakdown">{c.breakdown.length?c.breakdown.map(b=><span key={b.label}><span>{b.label}</span><b>{b.count}</b></span>):<span>No records in this period</span>}</div>}<small>{c.target}</small><div className="md-trend">{c.trend}</div></button>)}</div>
 <div className="md-top"><section className="md-card"><h2>Needs attention</h2><p>Current exceptions · highest severity first</p>{m.alerts.map(a=><button className="md-attention" key={a.label} onClick={()=>open(a.label,a.rows,'Current records matching the exception rule.',true)}><span>{a.label}<small>{statusText[a.severity]}</small></span><Badge state={a.severity}>{a.rows.length}</Badge></button>)}{!m.alerts.length&&<p className="md-empty">No exceptions found in records with usable dates.</p>}<p className="md-note">Stage SLA alerts unavailable: per-stage SLA targets are not configured. Missing dates are listed under Data quality. Feedback grace: 24 hours.</p></section>
 <section className="md-card"><h2>Recruitment journey</h2><p>Application cohort in selected period · unique candidates · observed through {range.end}</p><div className="md-tabs" role="group" aria-label="Recruitment view">{[['pipeline','Pipeline'],['conversion','Stage Conversion'],['routes','Actual Transitions']].map(([v,l])=><button key={v} aria-pressed={view===v} className={view===v?'selected':''} onClick={()=>setView(v)}>{l}</button>)}</div>
 {view!=='routes'?m.analysis.pipelineRows.map(r=><div className="md-stage" key={r.label}><span>{r.label}</span><button className="md-chart-bar" title={`${r.label}: ${r.reached} reached, ${r.passed} progressed, ${r.rejected} rejected, ${r.current} currently here`} onClick={()=>open(`${r.label} · ${view==='pipeline'?'Reached':'Passed'}`,m.stageRows(r.label,view==='pipeline'?'reached':'passed'))}><i style={{width:`${view==='pipeline'?r.reached/stageMax*100:r.conversion||0}%`,background:r.label===biggest?.label?'#FAA626':'#55C4EB'}}/></button>{num(view==='pipeline'?r.reached:pct(r.conversion),`${r.label} ${view==='pipeline'?'reached':'conversion'}`,m.stageRows(r.label,view==='pipeline'?'reached':'passed'))}<span className="md-stage-extra">{num(`${r.rejected} rejected`,`${r.label} rejected`,m.stageRows(r.label,'rejected'))}{num(`${r.current} here`,`${r.label} current`,m.stageRows(r.label,'current'))}</span></div>):m.analysis.transitions.length?m.analysis.transitions.map(r=><button className="md-attention" key={r.from+r.to} title={`${r.count} unique candidates recorded moving ${r.from} to ${r.to}`} onClick={()=>open(`${r.from} → ${r.to}`,m.routeRows(r))}><span>{r.from} → {r.to}</span><b>{r.count}</b></button>):<p className="md-empty">No recorded transitions for this cohort.</p>}
 <p className="md-note">Stages may be skipped; adjacent counts are not conversion rates. Conversion = passed ÷ reached at the same stage. HR Interview combines HR 1 and HR 2. {biggest?`Largest confirmed rejection count: ${biggest.label} (${biggest.rejected}).`:'No recorded rejection loss in this cohort.'}</p></section></div>
 <div className="md-row"><section className="md-card"><h2>Hires trend</h2><p>Cumulative event-dated hires in selected period</p>{hireTrendRows.length?<svg className="md-line-chart" viewBox="0 0 600 210" role="img" aria-label="Cumulative hires by month"><path d="M35 20V175H570" fill="none" stroke="#dce3e9"/><polyline fill="none" stroke="#55C4EB" strokeWidth="3" points={hireTrendRows.map((r,i)=>`${50+i*500/Math.max(1,hireTrendRows.length-1)},${170-r.cumulative/chartMax*140}`).join(' ')}/>{hireTrendRows.map((r,i)=><g key={r.month}><circle role="button" tabIndex="0" aria-label={`${r.month}: ${r.rows.length} hires, ${r.cumulative} cumulative`} cx={50+i*500/Math.max(1,hireTrendRows.length-1)} cy={170-r.cumulative/chartMax*140} r="5" fill="#58595B" onClick={()=>open(`${r.month} hires`,m.appRows(r.rows))} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(`${r.month} hires`,m.appRows(r.rows))}}}><title>{r.month}: {r.rows.length} monthly · {r.cumulative} cumulative · plan unavailable</title></circle>{(hireTrendRows.length<=12||i%Math.ceil(hireTrendRows.length/12)===0)&&<text x={50+i*500/Math.max(1,hireTrendRows.length-1)} y="195" textAnchor="middle">{r.month.slice(2)}</text>}</g>)}</svg>:<p className="md-empty">No data for this period.</p>}<p className="md-note">Monthly plan allocations are not configured, so no plan line or forecast is inferred. The current month may be incomplete.</p></section>
 <section className="md-card"><h2>Time to fill by department</h2><p>Opening to hire · target ≤50d · valid date pairs only</p>{fillDepartments.map(r=><div className="md-stage" key={r.department}><span>{r.department}</span><button className="md-chart-bar" title={`${mean(r.fill).toFixed(1)} days across ${r.fill.length} hires`} onClick={()=>open(r.department+' · time to fill',r.fill)}><i style={{width:`${mean(r.fill)/meanMax*100}%`,background:mean(r.fill)>60?'#F24B4B':mean(r.fill)>50?'#FAA626':'#A7D542'}}/></button>{num(`${rounded(mean(r.fill))}d`,r.department+' time to fill',r.fill)}<Badge state={mean(r.fill)>60?'risk':mean(r.fill)>50?'watch':'good'}/></div>)}{!fillDepartments.length&&<p className="md-empty">No valid opening-to-hire date pairs for this period.</p>}</section></div>
 <section className="md-card md-wide"><h2>Requested headcount vs hires by department</h2><p>All requested HC, including drafts · selected-period hires · sorted by gap</p><div className="table-wrap"><table><thead><tr><th>Department</th><th>Hires / HC</th><th>Unfilled gap</th><th>Open reqs / HC</th><th>Avg days open</th><th>Completion</th></tr></thead><tbody>{planRows.map(r=><tr key={r.department}><td>{r.department}</td><td>{num(r.hires.length,r.department+' hires',m.appRows(r.hires))} / {num(r.planned,r.department+' headcount',m.jobRows(r.jobs),'All requested headcount, including drafts.',true)}</td><td>{num(r.gap,r.department+' requested headcount',m.jobRows(r.jobs),`${r.planned} requested minus ${r.hires.length} period hires; not an open-requisition count.`)}</td><td>{num(`${r.open.length} / ${r.open.reduce((s,j)=>s+(Number(j.headcount)||1),0)}`,r.department+' open requisitions',m.jobRows(r.open),'Current open requisitions / headcount.',true)}</td><td>{num(r.averageOpen===null?'—':`${rounded(r.averageOpen)}d`,r.department+' open age',m.jobRows(r.open),'Average excludes missing opening dates.',true)}</td><td><button className="md-number" title={`${r.hires.length} hires / ${r.planned} requested HC`} onClick={()=>open(r.department+" completion",m.appRows(r.hires),`${r.hires.length} hires / ${r.planned} requested HC`)}><Badge state={progress(r.percent)}>{pct(r.percent)} · {statusText[progress(r.percent)]}</Badge></button></td></tr>)}<tr className="md-total"><td>Total · all departments</td><td>{num(m.hires.length,'Period hires',m.appRows(m.hires))} / {num(m.totalHC,'Requested headcount',m.jobRows(m.jobs),'All statuses.',true)}</td><td>{num(m.departments.reduce((s,r)=>s+r.gap,0),"Department gaps",m.departments.map(r=>({department:r.department,headcount:r.planned,hires:r.hires.length,gap:r.gap})))}</td><td>{num(`${m.open.length} / ${m.open.reduce((s,j)=>s+(Number(j.headcount)||1),0)}`,'Open requisitions',m.jobRows(m.open),'Current',true)}</td><td>{num(averageOpen===null?'—':`${rounded(averageOpen)}d`,'Open age',m.jobRows(totalOpenDated),'Weighted across dated open requisitions.',true)}</td><td><Badge state={progress(planRate)}>{pct(planRate)}</Badge></td></tr></tbody></table></div>{m.departments.length>8&&<button className="btn" onClick={()=>setAll(!all)}>{all?'Show top 8':'Show all departments'}</button>}<p className="md-note">Completion bands: &lt;50% at risk · 50–80% watch · &gt;80% on track. This is the requested-HC comparison, not verified 2026 plan pace. Overfilled departments do not cancel other departments’ gaps.</p></section>
 <div className="md-row"><section className="md-card"><h2>Talent source quality</h2><p>Selected application cohort · unique candidates · outcomes through cutoff</p><div className="table-wrap"><table><thead><tr><th>Source</th><th>Hire share</th><th>Hires</th><th>Applicants</th><th>Hire rate</th></tr></thead><tbody>{sources.map((r,i)=><tr key={r.source}><td><i className="md-dot" style={{background:colors[i%colors.length]}}/>{r.source}</td><td><button className="md-chart-bar" title={`${r.hires.length} / ${m.sourceHires} cohort hires`} onClick={()=>open(r.source+' hires',r.hires)}><i style={{width:`${m.sourceHires?r.hires.length/m.sourceHires*100:0}%`,background:colors[i%colors.length]}}/></button>{num(m.sourceHires?pct(r.hires.length/m.sourceHires*100):'—',r.source+' share',r.hires)}</td><td>{num(r.hires.length,r.source+' hires',r.hires)}</td><td>{num(r.applicants.length,r.source+' applicants',r.applicants)}</td><td>{num(pct(r.hires.length/r.applicants.length*100),r.source+' hire rate',r.applicants,`${r.hires.length} hires / ${r.applicants.length} applicants`)}</td></tr>)}</tbody></table></div>{!m.sources.length&&<p className="md-empty">No applications in this period.</p>}{sourceHidden.map(r=><button key={r.source} className="btn" title={`${r.hires.length} hires / ${r.applicants.length} applicants; ${pct(r.hires.length/r.applicants.length*100)} hire rate`} onClick={()=>open('Other source',r.applicants,`${r.hires.length} hired · ${pct(r.hires.length/r.applicants.length*100)} hire rate`)}>Other {pct(r.hires.length/m.sourceHires*100)} ⓘ</button>)}<p className="md-note">Colors identify sources, not performance. Uses each candidate’s recorded source.</p></section>
 <section className="md-card"><h2>Recruiter workload</h2><p>Current active applications and open requisitions</p><div className="table-wrap"><table><thead><tr><th>Recruiter</th><th>Active apps</th><th>Open reqs</th><th>Load</th></tr></thead><tbody>{m.recruiters.map(r=>{const state=r.apps.length>2*m.workloadMean?'risk':r.apps.length>1.5*m.workloadMean?'watch':'neutral';return <tr key={r.id} className={!r.apps.length&&!r.jobs.length?'md-zero':''}><td>{r.name}</td><td>{num(r.apps.length,r.name+' active applications',m.appRows(r.apps),'Shared applications count once per assigned recruiter.',true)}</td><td>{num(r.jobs.length,r.name+' open requisitions',m.jobRows(r.jobs),'Current',true)}</td><td><Badge state={state}>{r.apps.length?state==='neutral'?'Within band':statusText[state]:'No load'}</Badge></td></tr>})}</tbody></table></div><p className="md-note">Average {m.workloadMean.toFixed(1)} active applications. Watch &gt;1.5× mean; at risk &gt;2×. Shared assignments count for each owner, so recruiter totals are not a unique team total.</p></section></div>
 <details className="md-card md-quality"><summary>Data quality and calculation coverage</summary>{m.quality.map(q=><button className="md-attention" key={q.label} onClick={()=>open(q.label,q.rows,'Review only; no records are changed.',true)}><span>{q.label}</span><b>{q.rows.length}</b></button>)}<p className="md-note">Hires now use recorded Hired events, not last-edit dates or undated records. They count application IDs; multiple hired applications for the same candidate are flagged. Pipeline counts unique candidates from its application cohort, so it is not the same as the period hire-event total. Requisition records and requested headcount are distinct units. Historical position status, annual plan membership, monthly allocations, stage SLAs and confirmed joining linkage are not verified.</p></details>{detail&&<Detail key={detail.title+detail.scope} detail={detail} onClose={()=>setDetail(null)}/>}
 </div>;
}
